//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  journal: Journal;
  journalConnection: JournalConnection;
  issues: Issues;
  issuesConnection: IssuesConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryJournalArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryJournalConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<JournalFilter>;
};


export type QueryIssuesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryIssuesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<IssuesFilter>;
};

export type DocumentFilter = {
  journal?: InputMaybe<JournalFilter>;
  issues?: InputMaybe<IssuesFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Journal | Issues | Folder;

export type Journal = Node & Document & {
  __typename?: 'Journal';
  titleZh: Scalars['String']['output'];
  titleEn: Scalars['String']['output'];
  category: Scalars['String']['output'];
  categoryZh?: Maybe<Scalars['String']['output']>;
  categoryEn?: Maybe<Scalars['String']['output']>;
  coverImage?: Maybe<Scalars['String']['output']>;
  excerptZh?: Maybe<Scalars['String']['output']>;
  excerptEn?: Maybe<Scalars['String']['output']>;
  authorZh?: Maybe<Scalars['String']['output']>;
  authorEn?: Maybe<Scalars['String']['output']>;
  publishedAt?: Maybe<Scalars['String']['output']>;
  readingTime?: Maybe<Scalars['Float']['output']>;
  requiresMembership?: Maybe<Scalars['Boolean']['output']>;
  issue?: Maybe<Scalars['String']['output']>;
  collection?: Maybe<Scalars['String']['output']>;
  relatedProductIds?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  bodyZh?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  bodyEn?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type JournalFilter = {
  titleZh?: InputMaybe<StringFilter>;
  titleEn?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  categoryZh?: InputMaybe<StringFilter>;
  categoryEn?: InputMaybe<StringFilter>;
  coverImage?: InputMaybe<ImageFilter>;
  excerptZh?: InputMaybe<StringFilter>;
  excerptEn?: InputMaybe<StringFilter>;
  authorZh?: InputMaybe<StringFilter>;
  authorEn?: InputMaybe<StringFilter>;
  publishedAt?: InputMaybe<DatetimeFilter>;
  readingTime?: InputMaybe<NumberFilter>;
  requiresMembership?: InputMaybe<BooleanFilter>;
  issue?: InputMaybe<StringFilter>;
  collection?: InputMaybe<StringFilter>;
  relatedProductIds?: InputMaybe<StringFilter>;
  bodyZh?: InputMaybe<StringFilter>;
  bodyEn?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type JournalConnectionEdges = {
  __typename?: 'JournalConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Journal>;
};

export type JournalConnection = Connection & {
  __typename?: 'JournalConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<JournalConnectionEdges>>>;
};

export type Issues = Node & Document & {
  __typename?: 'Issues';
  issueId: Scalars['String']['output'];
  titleZh: Scalars['String']['output'];
  titleEn: Scalars['String']['output'];
  bodyZh?: Maybe<Scalars['String']['output']>;
  bodyEn?: Maybe<Scalars['String']['output']>;
  coverImage?: Maybe<Scalars['String']['output']>;
  articleCount?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type IssuesFilter = {
  issueId?: InputMaybe<StringFilter>;
  titleZh?: InputMaybe<StringFilter>;
  titleEn?: InputMaybe<StringFilter>;
  bodyZh?: InputMaybe<StringFilter>;
  bodyEn?: InputMaybe<StringFilter>;
  coverImage?: InputMaybe<ImageFilter>;
  articleCount?: InputMaybe<NumberFilter>;
};

export type IssuesConnectionEdges = {
  __typename?: 'IssuesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Issues>;
};

export type IssuesConnection = Connection & {
  __typename?: 'IssuesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<IssuesConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateJournal: Journal;
  createJournal: Journal;
  updateIssues: Issues;
  createIssues: Issues;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateJournalArgs = {
  relativePath: Scalars['String']['input'];
  params: JournalMutation;
};


export type MutationCreateJournalArgs = {
  relativePath: Scalars['String']['input'];
  params: JournalMutation;
};


export type MutationUpdateIssuesArgs = {
  relativePath: Scalars['String']['input'];
  params: IssuesMutation;
};


export type MutationCreateIssuesArgs = {
  relativePath: Scalars['String']['input'];
  params: IssuesMutation;
};

export type DocumentUpdateMutation = {
  journal?: InputMaybe<JournalMutation>;
  issues?: InputMaybe<IssuesMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  journal?: InputMaybe<JournalMutation>;
  issues?: InputMaybe<IssuesMutation>;
};

export type JournalMutation = {
  titleZh?: InputMaybe<Scalars['String']['input']>;
  titleEn?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  categoryZh?: InputMaybe<Scalars['String']['input']>;
  categoryEn?: InputMaybe<Scalars['String']['input']>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  excerptZh?: InputMaybe<Scalars['String']['input']>;
  excerptEn?: InputMaybe<Scalars['String']['input']>;
  authorZh?: InputMaybe<Scalars['String']['input']>;
  authorEn?: InputMaybe<Scalars['String']['input']>;
  publishedAt?: InputMaybe<Scalars['String']['input']>;
  readingTime?: InputMaybe<Scalars['Float']['input']>;
  requiresMembership?: InputMaybe<Scalars['Boolean']['input']>;
  issue?: InputMaybe<Scalars['String']['input']>;
  collection?: InputMaybe<Scalars['String']['input']>;
  relatedProductIds?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  bodyZh?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  bodyEn?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type IssuesMutation = {
  issueId?: InputMaybe<Scalars['String']['input']>;
  titleZh?: InputMaybe<Scalars['String']['input']>;
  titleEn?: InputMaybe<Scalars['String']['input']>;
  bodyZh?: InputMaybe<Scalars['String']['input']>;
  bodyEn?: InputMaybe<Scalars['String']['input']>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  articleCount?: InputMaybe<Scalars['Float']['input']>;
};

export type JournalPartsFragment = { __typename: 'Journal', titleZh: string, titleEn: string, category: string, categoryZh?: string | null, categoryEn?: string | null, coverImage?: string | null, excerptZh?: string | null, excerptEn?: string | null, authorZh?: string | null, authorEn?: string | null, publishedAt?: string | null, readingTime?: number | null, requiresMembership?: boolean | null, issue?: string | null, collection?: string | null, relatedProductIds?: Array<string | null> | null, bodyZh?: Array<string | null> | null, bodyEn?: Array<string | null> | null, body?: any | null };

export type IssuesPartsFragment = { __typename: 'Issues', issueId: string, titleZh: string, titleEn: string, bodyZh?: string | null, bodyEn?: string | null, coverImage?: string | null, articleCount?: number | null };

export type JournalQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type JournalQuery = { __typename?: 'Query', journal: { __typename: 'Journal', id: string, titleZh: string, titleEn: string, category: string, categoryZh?: string | null, categoryEn?: string | null, coverImage?: string | null, excerptZh?: string | null, excerptEn?: string | null, authorZh?: string | null, authorEn?: string | null, publishedAt?: string | null, readingTime?: number | null, requiresMembership?: boolean | null, issue?: string | null, collection?: string | null, relatedProductIds?: Array<string | null> | null, bodyZh?: Array<string | null> | null, bodyEn?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type JournalConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<JournalFilter>;
}>;


export type JournalConnectionQuery = { __typename?: 'Query', journalConnection: { __typename?: 'JournalConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'JournalConnectionEdges', cursor: string, node?: { __typename: 'Journal', id: string, titleZh: string, titleEn: string, category: string, categoryZh?: string | null, categoryEn?: string | null, coverImage?: string | null, excerptZh?: string | null, excerptEn?: string | null, authorZh?: string | null, authorEn?: string | null, publishedAt?: string | null, readingTime?: number | null, requiresMembership?: boolean | null, issue?: string | null, collection?: string | null, relatedProductIds?: Array<string | null> | null, bodyZh?: Array<string | null> | null, bodyEn?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type IssuesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type IssuesQuery = { __typename?: 'Query', issues: { __typename: 'Issues', id: string, issueId: string, titleZh: string, titleEn: string, bodyZh?: string | null, bodyEn?: string | null, coverImage?: string | null, articleCount?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type IssuesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<IssuesFilter>;
}>;


export type IssuesConnectionQuery = { __typename?: 'Query', issuesConnection: { __typename?: 'IssuesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'IssuesConnectionEdges', cursor: string, node?: { __typename: 'Issues', id: string, issueId: string, titleZh: string, titleEn: string, bodyZh?: string | null, bodyEn?: string | null, coverImage?: string | null, articleCount?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const JournalPartsFragmentDoc = gql`
    fragment JournalParts on Journal {
  __typename
  titleZh
  titleEn
  category
  categoryZh
  categoryEn
  coverImage
  excerptZh
  excerptEn
  authorZh
  authorEn
  publishedAt
  readingTime
  requiresMembership
  issue
  collection
  relatedProductIds
  bodyZh
  bodyEn
  body
}
    `;
export const IssuesPartsFragmentDoc = gql`
    fragment IssuesParts on Issues {
  __typename
  issueId
  titleZh
  titleEn
  bodyZh
  bodyEn
  coverImage
  articleCount
}
    `;
export const JournalDocument = gql`
    query journal($relativePath: String!) {
  journal(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...JournalParts
  }
}
    ${JournalPartsFragmentDoc}`;
export const JournalConnectionDocument = gql`
    query journalConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: JournalFilter) {
  journalConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...JournalParts
      }
    }
  }
}
    ${JournalPartsFragmentDoc}`;
export const IssuesDocument = gql`
    query issues($relativePath: String!) {
  issues(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...IssuesParts
  }
}
    ${IssuesPartsFragmentDoc}`;
export const IssuesConnectionDocument = gql`
    query issuesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: IssuesFilter) {
  issuesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...IssuesParts
      }
    }
  }
}
    ${IssuesPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      journal(variables: JournalQueryVariables, options?: C): Promise<{data: JournalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: JournalQueryVariables, query: string}> {
        return requester<{data: JournalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: JournalQueryVariables, query: string}, JournalQueryVariables>(JournalDocument, variables, options);
      },
    journalConnection(variables?: JournalConnectionQueryVariables, options?: C): Promise<{data: JournalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: JournalConnectionQueryVariables, query: string}> {
        return requester<{data: JournalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: JournalConnectionQueryVariables, query: string}, JournalConnectionQueryVariables>(JournalConnectionDocument, variables, options);
      },
    issues(variables: IssuesQueryVariables, options?: C): Promise<{data: IssuesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: IssuesQueryVariables, query: string}> {
        return requester<{data: IssuesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: IssuesQueryVariables, query: string}, IssuesQueryVariables>(IssuesDocument, variables, options);
      },
    issuesConnection(variables?: IssuesConnectionQueryVariables, options?: C): Promise<{data: IssuesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: IssuesConnectionQueryVariables, query: string}> {
        return requester<{data: IssuesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: IssuesConnectionQueryVariables, query: string}, IssuesConnectionQueryVariables>(IssuesConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  