import { toyProducts } from "./catalog-toys.js";

export const PRODUCT_POLICY_VERSION = "product-policy-2026-07-23";

const DEFAULT_SOURCING_POLICY = Object.freeze({
  sourceCountry: "China",
  sourceType: "Third-party supplier",
  fulfillmentLabels: ["Sourced After Order", "Third-Party Fulfilled"],
  processingTime: "Details pending verification",
  internationalShippingTime: "Details pending verification",
  returnWindowDays: null,
  returnEligible: null,
  cancellationDeadline: "Before supplier purchasing begins",
  finalSale: null,
  returnShippingPayer: "Details pending verification",
  restockingFee: "Details pending verification",
  damageReportDeadline: "Contact support promptly after delivery; item-specific deadline pending verification",
  supplierReturnConditions: "Details pending verification",
  dutiesTreatment: "Estimated import charges, if any, may be collected separately at delivery",
  safetyWarning: "Review item-specific materials, dimensions, age guidance, and warnings before use; details pending verification",
  imageSource: "Details pending verification",
  supplierInfoNotice: "Product details are based partly on supplier-provided information and remain subject to verification",
  policyVersion: PRODUCT_POLICY_VERSION,
});

function withSourcingPolicy(product) {
  return {
    ...DEFAULT_SOURCING_POLICY,
    ...product,
    fulfillmentLabels: product.fulfillmentLabels || DEFAULT_SOURCING_POLICY.fulfillmentLabels,
    images: product.images || [product.image],
    variants: product.variants || [{ id: "standard", label: "Standard", price: product.price }],
  };
}

const metalProducts = [
  {
    id: "metal-bracket",
    collection: "metal",
    image: "/assets/metal/bracket.png",
    price: 128,
    material: "316L",
    zh: { name: "316L 精密安装支架", desc: "不锈钢打印支架，适合机柜与实验台固定。" },
    en: { name: "316L mounting bracket", desc: "Stainless print for enclosure and lab-bench mounting." },
  },
  {
    id: "drone-arm",
    collection: "metal",
    image: "/assets/metal/drone.png",
    price: 268,
    material: "AlSi10Mg",
    zh: { name: "AlSi10Mg 无人机臂架", desc: "轻量铝合金臂架，喷砂表面，孔位预留。" },
    en: { name: "AlSi10Mg drone arm", desc: "Lightweight aluminum arm with bead-blast finish." },
  },
  {
    id: "titanium-hinge",
    collection: "metal",
    image: "/assets/metal/gen-metal-hinge.png",
    price: 398,
    material: "TC4",
    zh: { name: "TC4 航空铰链座", desc: "钛合金高强度铰链结构，面向装机与工装。" },
    en: { name: "TC4 aerospace hinge", desc: "Titanium high-load hinge for builds and fixtures." },
  },
  {
    id: "lattice-heatsink",
    collection: "metal",
    image: "/assets/metal/gen-metal-lattice.png",
    price: 188,
    material: "AlSi10Mg",
    zh: { name: "点阵散热支架", desc: "轻量化点阵结构，兼顾散热与减重。" },
    en: { name: "Lattice heat bracket", desc: "Lightweight lattice for cooling and mass reduction." },
  },
  {
    id: "gearbox-housing",
    collection: "metal",
    image: "/assets/metal/gen-metal-gearbox.png",
    price: 328,
    material: "AlSi10Mg",
    zh: { name: "铝合金齿轮箱壳体", desc: "复杂内腔一体打印，减少装配件数量。" },
    en: { name: "Aluminum gearbox housing", desc: "Complex cavity in one print, fewer assemblies." },
  },
  {
    id: "copper-manifold",
    collection: "metal",
    image: "/assets/metal/gen-metal-copper.png",
    price: 456,
    material: "CuCrZr",
    zh: { name: "铜铬锆换热歧管", desc: "高导热铜合金，适合热交换与冷却回路。" },
    en: { name: "CuCrZr heat manifold", desc: "High-conductivity copper for cooling loops." },
  },
  {
    id: "tool-mount",
    collection: "metal",
    image: "/assets/metal/bracket.png",
    price: 159,
    material: "17-4PH",
    zh: { name: "17-4PH 工具夹持座", desc: "模具钢方向强度，适合夹具与工装。" },
    en: { name: "17-4PH tool mount", desc: "Hardened steel path for fixtures and jigs." },
  },
  {
    id: "cnc-adapter",
    collection: "metal",
    image: "/assets/metal/cnc.jpg",
    price: 210,
    material: "316L",
    zh: { name: "机床过渡法兰", desc: "不锈钢法兰接口，适配常见机床工装。" },
    en: { name: "Machine adapter flange", desc: "Stainless flange for common machine fixtures." },
  },
  {
    id: "lab-rail",
    collection: "metal",
    image: "/assets/metal/lab.jpg",
    price: 175,
    material: "17-4PH",
    zh: { name: "实验台导轨座", desc: "高强度导轨安装座，适合实验室改装。" },
    en: { name: "Lab rail mount", desc: "High-strength rail mount for lab upgrades." },
  },
  {
    id: "engine-bracket",
    collection: "metal",
    image: "/assets/metal/engine.jpg",
    price: 520,
    material: "TC4",
    zh: { name: "动力总成支撑架", desc: "钛合金支撑结构，面向高振动工况。" },
    en: { name: "Powertrain support", desc: "Titanium support for high-vibration duty." },
  },
  {
    id: "shop-jig",
    collection: "metal",
    image: "/assets/metal/shopfloor.jpg",
    price: 142,
    material: "316L",
    zh: { name: "车间定位夹具", desc: "不锈钢定位夹具，小批量生产常用。" },
    en: { name: "Shop locating jig", desc: "Stainless locating jig for small-batch runs." },
  },
  {
    id: "drone-plate",
    collection: "metal",
    image: "/assets/metal/drone.png",
    price: 98,
    material: "AlSi10Mg",
    zh: { name: "机臂连接底板", desc: "轻量底板，配合臂架快速换装。" },
    en: { name: "Arm link plate", desc: "Lightweight plate for quick arm swaps." },
  },
];

const portraitProducts = [
  {
    id: "portrait-bust",
    collection: "portrait",
    image: "/assets/portrait/bust.png",
    price: 299,
    material: "SLA Resin",
    zh: { name: "15cm 半身手办", desc: "照片建模半身像，树脂细节，底座可选。" },
    en: { name: "15cm portrait bust", desc: "Photo-modeled bust in resin with optional base." },
  },
  {
    id: "full-figurine",
    collection: "portrait",
    image: "/assets/portrait/figurine.png",
    price: 499,
    material: "SLA Resin",
    zh: { name: "20cm 全身手办", desc: "全身姿势确认后打印，适合礼物与纪念。" },
    en: { name: "20cm full figurine", desc: "Full-body print after pose approval, gift-ready." },
  },
  {
    id: "elder-bust",
    collection: "portrait",
    image: "/assets/portrait/gen-portrait-elder.png",
    price: 349,
    material: "SLA Resin",
    zh: { name: "长辈纪念半身像", desc: "细节皮肤质感，适合家庭纪念与送礼。" },
    en: { name: "Elder memorial bust", desc: "Detailed skin finish for family keepsakes." },
  },
  {
    id: "couple-set",
    collection: "portrait",
    image: "/assets/portrait/gen-portrait-couple.png",
    price: 699,
    material: "SLA Resin",
    zh: { name: "双人手办礼盒", desc: "双人组合 + 礼盒包装，纪念日向产品。" },
    en: { name: "Couple figurine set", desc: "Pair set with gift box for anniversaries." },
  },
  {
    id: "child-bust",
    collection: "portrait",
    image: "/assets/portrait/gen-portrait-child.png",
    price: 279,
    material: "SLA Resin",
    zh: { name: "儿童成长半身像", desc: "柔和上色，记录成长节点。" },
    en: { name: "Child growth bust", desc: "Soft painted finish for childhood milestones." },
  },
  {
    id: "grad-figurine",
    collection: "portrait",
    image: "/assets/portrait/gen-portrait-grad.png",
    price: 459,
    material: "SLA Resin",
    zh: { name: "毕业纪念全身像", desc: "学士服造型，毕业季热销款。" },
    en: { name: "Graduation figurine", desc: "Cap-and-gown keepsake for graduation season." },
  },
  {
    id: "classic-bust",
    collection: "portrait",
    image: "/assets/portrait/museum.jpg",
    price: 389,
    material: "SLA Resin",
    zh: { name: "经典雕塑风半身像", desc: "博物馆雕塑风格表面，适合收藏展示。" },
    en: { name: "Classic sculpture bust", desc: "Museum-style finish for display collections." },
  },
  {
    id: "gallery-edition",
    collection: "portrait",
    image: "/assets/portrait/gallery.jpg",
    price: 520,
    material: "SLA Resin",
    zh: { name: "画廊陈列版手办", desc: "更高底座与打光友好表面。" },
    en: { name: "Gallery display edition", desc: "Taller base and light-friendly finish." },
  },
  {
    id: "pet-figurine",
    collection: "portrait",
    image: "/assets/portrait/figurine.png",
    price: 259,
    material: "SLA Resin",
    zh: { name: "宠物定制全身像", desc: "按宠物照片建模，小型桌面尺寸。" },
    en: { name: "Pet custom figurine", desc: "Photo-modeled pet figure in desk size." },
  },
  {
    id: "family-set",
    collection: "portrait",
    image: "/assets/portrait/gen-portrait-couple.png",
    price: 699,
    material: "SLA Resin",
    zh: { name: "家庭三人礼盒", desc: "三人手办组合，含统一底座与礼盒。" },
    en: { name: "Family trio gift set", desc: "Three-figure set with shared base and gift box." },
  },
  {
    id: "mini-bust",
    collection: "portrait",
    image: "/assets/portrait/bust.png",
    price: 169,
    material: "SLA Resin",
    zh: { name: "8cm 迷你半身像", desc: "入门尺寸，适合批量纪念品。" },
    en: { name: "8cm mini bust", desc: "Entry size for batch keepsakes." },
  },
  {
    id: "display-base",
    collection: "portrait",
    image: "/assets/portrait/bust.png",
    price: 45,
    material: "SLA Resin",
    zh: { name: "展示底座套装", desc: "手办通用底座与铭牌位，单独加购。" },
    en: { name: "Display base set", desc: "Universal figurine bases with nameplate space." },
  },
];

export const products = [
  ...metalProducts.map(withSourcingPolicy),
  ...toyProducts.map(withSourcingPolicy),
  ...portraitProducts.map(withSourcingPolicy),
];

export function getProduct(id) {
  return products.find((p) => p.id === id);
}
