export const ORDER_TERMS_VERSION = "order-terms-2026-07-26";
export const SHIPPING_RULE_VERSION = "shipping-rules-2026-07-26";
export const TAX_RULE_VERSION = "tax-rules-2026-07-26";
export const LANDED_COST_RULE_VERSION = "landed-cost-rules-2026-07-26";

export const COUNTRY_FULFILLMENT_RULES = Object.freeze({
  US: {
    countryCode: "US",
    enabled: true,
    currency: "USD",
    shippingMode: "WEIGHT_BASED",
    incoterm: "DAP",
    taxCalculationMode: "STRIPE_TAX",
    dutyCalculationMode: "MANUAL_ESTIMATE",
    estimatedCustomsDaysMin: 2,
    estimatedCustomsDaysMax: 5,
    remoteAreaSurchargeEnabled: false,
    restrictedCategories: [],
    addressRequirements: {
      regionLabel: { zh: "州", en: "State" },
      postalLabel: { zh: "邮编", en: "ZIP code" },
      postalPattern: "^\\d{5}(-\\d{4})?$",
      required: ["fullName", "addressLine1", "city", "stateProvinceRegion", "postalCode"],
    },
    fallbackShippingFee: 1800,
    fallbackShippingDaysMin: 6,
    fallbackShippingDaysMax: 12,
    weightTiers: [
      { maxGrams: 500, fee: 1200 },
      { maxGrams: 1500, fee: 1800 },
      { maxGrams: 4000, fee: 2800 },
      { maxGrams: 8000, fee: 4600 },
    ],
    landedCost: {
      dutyRateBps: 0,
      importTaxRateBps: 0,
      brokerageFee: 0,
      customsProcessingFee: 0,
    },
  },
  CA: {
    countryCode: "CA",
    enabled: true,
    currency: "USD",
    shippingMode: "WEIGHT_BASED",
    incoterm: "DAP",
    taxCalculationMode: "STRIPE_TAX",
    dutyCalculationMode: "MANUAL_ESTIMATE",
    estimatedCustomsDaysMin: 3,
    estimatedCustomsDaysMax: 7,
    remoteAreaSurchargeEnabled: true,
    restrictedCategories: ["fragrance", "dangerous_goods"],
    addressRequirements: {
      regionLabel: { zh: "省份", en: "Province" },
      postalLabel: { zh: "邮编", en: "Postal code" },
      postalPattern: "^[A-Za-z]\\d[A-Za-z][ -]?\\d[A-Za-z]\\d$",
      required: ["fullName", "addressLine1", "city", "stateProvinceRegion", "postalCode", "phone"],
    },
    fallbackShippingFee: 2800,
    fallbackShippingDaysMin: 8,
    fallbackShippingDaysMax: 16,
    weightTiers: [
      { maxGrams: 500, fee: 2200 },
      { maxGrams: 1500, fee: 2800 },
      { maxGrams: 4000, fee: 4200 },
      { maxGrams: 8000, fee: 6800 },
    ],
    landedCost: {
      dutyRateBps: 600,
      importTaxRateBps: 0,
      brokerageFee: 1500,
      customsProcessingFee: 0,
    },
  },
  GB: {
    countryCode: "GB",
    enabled: true,
    currency: "USD",
    shippingMode: "WEIGHT_BASED",
    incoterm: "DAP",
    taxCalculationMode: "STRIPE_TAX",
    dutyCalculationMode: "MANUAL_ESTIMATE",
    estimatedCustomsDaysMin: 3,
    estimatedCustomsDaysMax: 8,
    remoteAreaSurchargeEnabled: true,
    restrictedCategories: ["fragrance", "dangerous_goods"],
    addressRequirements: {
      regionLabel: { zh: "地区", en: "Region" },
      postalLabel: { zh: "邮编", en: "Postcode" },
      postalPattern: "^[A-Za-z0-9][A-Za-z0-9 ]{4,9}$",
      required: ["fullName", "addressLine1", "city", "postalCode", "phone"],
    },
    fallbackShippingFee: 3600,
    fallbackShippingDaysMin: 9,
    fallbackShippingDaysMax: 18,
    weightTiers: [
      { maxGrams: 500, fee: 2600 },
      { maxGrams: 1500, fee: 3600 },
      { maxGrams: 4000, fee: 5600 },
      { maxGrams: 8000, fee: 8400 },
    ],
    landedCost: {
      dutyRateBps: 800,
      importTaxRateBps: 0,
      brokerageFee: 1800,
      customsProcessingFee: 0,
    },
  },
  AU: {
    countryCode: "AU",
    enabled: true,
    currency: "USD",
    shippingMode: "WEIGHT_BASED",
    incoterm: "DAP",
    taxCalculationMode: "STRIPE_TAX",
    dutyCalculationMode: "MANUAL_ESTIMATE",
    estimatedCustomsDaysMin: 4,
    estimatedCustomsDaysMax: 9,
    remoteAreaSurchargeEnabled: true,
    restrictedCategories: ["fragrance", "dangerous_goods"],
    addressRequirements: {
      regionLabel: { zh: "州/领地", en: "State / territory" },
      postalLabel: { zh: "邮编", en: "Postcode" },
      postalPattern: "^\\d{4}$",
      required: ["fullName", "addressLine1", "city", "stateProvinceRegion", "postalCode", "phone"],
    },
    fallbackShippingFee: 4200,
    fallbackShippingDaysMin: 10,
    fallbackShippingDaysMax: 20,
    weightTiers: [
      { maxGrams: 500, fee: 3000 },
      { maxGrams: 1500, fee: 4200 },
      { maxGrams: 4000, fee: 6600 },
      { maxGrams: 8000, fee: 9800 },
    ],
    landedCost: {
      dutyRateBps: 500,
      importTaxRateBps: 0,
      brokerageFee: 1800,
      customsProcessingFee: 0,
    },
  },
  CN: {
    countryCode: "CN",
    enabled: false,
    currency: "USD",
    shippingMode: "FALLBACK_ESTIMATE",
    incoterm: "DAP",
    taxCalculationMode: "NOT_APPLICABLE",
    dutyCalculationMode: "MANUAL_ESTIMATE",
    estimatedCustomsDaysMin: 4,
    estimatedCustomsDaysMax: 12,
    remoteAreaSurchargeEnabled: true,
    restrictedCategories: [],
    addressRequirements: {
      regionLabel: { zh: "省/自治区/直辖市", en: "Province / region" },
      postalLabel: { zh: "邮编", en: "Postal code" },
      postalPattern: "^\\d{6}$",
      required: ["fullName", "addressLine1", "city", "stateProvinceRegion", "postalCode", "phone"],
    },
    fallbackShippingFee: 3000,
    fallbackShippingDaysMin: 7,
    fallbackShippingDaysMax: 18,
    weightTiers: [],
    landedCost: {
      dutyRateBps: 0,
      importTaxRateBps: 0,
      brokerageFee: 0,
      customsProcessingFee: 0,
    },
  },
});

export const SUPPORTED_COUNTRIES = Object.freeze(Object.values(COUNTRY_FULFILLMENT_RULES));

export const ORDER_TERMS = Object.freeze({
  zh: {
    acknowledgement: [
      "本商品由傲马在下单后按需采购或安排制作。",
      "我已查看预计采购及配送时间。",
      "订单进入采购流程后，不支持因改变主意而取消、退货或换货。",
      "我已检查商品尺寸、材质、来源、配送方式、税费及进口费用。",
      "若商品损坏、错发或与描述重大不符，我仍可依据售后政策申请处理。",
    ],
    policy:
      "由于本订单属于按需采购、限量调货或定制化采购，傲马会在收到订单后专门向供应商采购。订单进入采购流程后，原则上不接受因改变主意、尺寸选择错误、颜色偏好或个人主观原因提出的取消、退货或换货。若收到的商品存在运输损坏、错发、缺失、明显质量问题或与商品描述重大不符，请在签收后48小时内提交照片及订单信息。经审核确认后，我们将依据实际情况提供补发、维修、换货、部分退款或退款处理。本政策不限制消费者依据其所在地强制性法律享有的权利。",
  },
  en: {
    acknowledgement: [
      "Orbmare will source or arrange production for this item after the order is placed.",
      "I have reviewed the estimated sourcing and delivery window.",
      "Once procurement begins, cancellation, returns, or exchanges for a change of mind are not available.",
      "I have checked the item size, material, origin, shipping method, taxes, and import-cost treatment.",
      "If the item arrives damaged, incorrect, missing, or materially different from its description, I may still request support under the after-sales policy.",
    ],
    policy:
      "Because this order may involve on-demand sourcing, limited allocation, or customized procurement, Orbmare will purchase or arrange the item specifically after the order is placed. Once procurement begins, cancellation, returns, or exchanges are generally not available for change of mind, wrong size selection, color preference, or other subjective reasons. If an item arrives damaged in transit, incorrect, missing, plainly defective, or materially different from its description, submit photos and order details within 48 hours of delivery. After review, Orbmare may provide replacement, repair, exchange, partial refund, or refund as appropriate. This policy does not limit any mandatory consumer rights available under the customer’s local law.",
  },
});
